version: '3'
services:
  esmaster:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: esmaster
    environment:
      - node.name=esmaster
      #- node.master=true
      - node.voting_only=false 
      - node.data=false 
      - node.ingest=false 
      - node.ml=false 
      - xpack.ml.enabled=true 
      - cluster.remote.connect=false
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=esclient1,esclient2
      - cluster.initial_master_nodes=esmaster,esclient1,esclient2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - datamaster:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - elastic
    restart_policy:
      condition: on-failure
      delay: 30s
      max_attempts: 3
      window: 120s
  esclient1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: esclient1
    environment:
      - node.name=esclient1
      #- node.master=false
      - node.voting_only=false 
      - node.data=true 
      - node.ingest=false 
      - node.ml=false 
      - cluster.remote.connect=false 
      #would be great to make it an ingest node for pipeline process
      #by default ingest is set to true for all nodes
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=esmaster,esclient2
      - cluster.initial_master_nodes=esmaster,esclient1,esclient2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataclient1:/usr/share/elasticsearch/data
    networks:
      - elastic
    restart_policy:
     condition: on-failure
      delay: 30s
      max_attempts: 3
      window: 120s
  esclient2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: esclient2
    environment:
      - node.name=esclient2
      #- node.master=false 
      - node.voting_only=false 
      - node.data=true 
      - node.ingest=false 
      - node.ml=false 
      - cluster.remote.connect=false 
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=esmaster,esclient1
      - cluster.initial_master_nodes=esmaster,esclient1,esclient2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataclient2:/usr/share/elasticsearch/data
    networks:
      - elastic
    restart_policy:
      condition: on-failure
      delay: 30s
      max_attempts: 3
      window: 120s

volumes:
  datamaster:
    driver: local
  dataclient1:
    driver: local
  dataclient2:
    driver: local

networks:
  elastic:
    driver: bridge
