version: '3'
services:
  esmaster:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: esmaster
    environment:
      - node.name=esmaster
      - node.master=true
      - node.voting_only=false 
      - node.data=false 
      - node.ingest=false 
      - node.ml=false 
      - xpack.ml.enabled=true 
      - cluster.remote.connect=false
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=esdata1,esdata2
      - cluster.initial_master_nodes=esmaster,esdata1,esdata2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - datamaster:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - elastic
  esdata1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: esdata1
    environment:
      - node.name=esdata1
      - node.master=false
      - node.voting_only=false 
      - node.data=true 
      - node.ingest=false 
      - node.ml=false 
      - cluster.remote.connect=false 
      #would be great to make it an ingest node for pipeline process
      #by default ingest is set to true for all nodes
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=esmaster,esdata2
      - cluster.initial_master_nodes=esmaster,esdata1,esdata2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data1:/usr/share/elasticsearch/data
    networks:
      - elastic
  esdata2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: esdata2
    environment:
      - node.name=esdata2
      - node.master=false 
      - node.voting_only=false 
      - node.data=true 
      - node.ingest=false 
      - node.ml=false 
      - cluster.remote.connect=false 
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=esmaster,esdata1
      - cluster.initial_master_nodes=esmaster,esdata1,esdata2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data2:/usr/share/elasticsearch/data
    networks:
      - elastic
volumes:
  datamaster:
    driver: local
  data1:
    driver: local
  data2:
    driver: local

networks:
  elastic:
    driver: bridge
