version: '3'
services:
  esmaster:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: esmaster
    environment:
      - node.name=esmaster
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=esclient1,esclient2
      - cluster.initial_master_nodes=esmaster,esclient1,esclient2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - datamaster:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  esclient1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: esclient1
    environment:
      - node.name=esclient1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=esmaster,esclient2
      - cluster.initial_master_nodes=esmaster,esclient1,esclient2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataclient1:/usr/share/elasticsearch/data
    networks:
      - elastic
  esclient2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: esclient2
    environment:
      - node.name=esclient2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=esmaster,esclient1
      - cluster.initial_master_nodes=esmaster,esclient1,esclient2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataclient2:/usr/share/elasticsearch/data
    networks:
      - elastic

volumes:
  datamaster:
    driver: local
  dataclient1:
    driver: local
  dataclient2:
    driver: local

networks:
  elastic:
    driver: bridge
