version: "3"

services:       #Services à exécuter
  apache_img_1:     #Premier serveur apache à démarrer / Service 1
    container_name: ${COMPOSE_PROJECT_NAME}_apache_con_1
    build: ./apache/1     #tag de l'image construite
    expose:               #Ports de notre service (port interne)
      - ${APACHE_EXPOSED_PORT}
    networks:
      public_net:           #Custom name
        ipv4_address: ${APACHE_1_IP}
  apache_img_2:       #Deuxième serveur apache à démarrer / Service 2
    container_name: ${COMPOSE_PROJECT_NAME}_apache_con_2
    build: ./apache/2
    expose:
      - ${APACHE_EXPOSED_PORT}
    networks:
      public_net:
        ipv4_address: ${APACHE_2_IP}
  haproxy:            #Service haproxy : load balancing + proxy pour TCP et applications HTTP
    build: ./haproxy  
    ports:
      - 80:80
    expose:
      - 80
    networks:
      public_net:
        ipv4_address: ${HA_PROXY_IP}
    environment:      #Passage de notre shell actuel aux services des conteneurs ci-dessous
      - APACHE_1_IP=${APACHE_1_IP}
      - APACHE_2_IP=${APACHE_2_IP}
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
    restart: always
    
  elasticsearch:
    build : ./elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    networks:
      - elknet
    #data persitence
    volumes:
      - esdata:/usr/share/elasticsearch/data
      
  kibana:
    build : ./kibana
    container_name: kibana
    environment:
      SERVER_NAME : kibana
      #accessing elasticsearch url and port inside the subnet
      ELASTICSEARCH_URL : http://elasticsearch:9200
    networks:
      - elknet
  
  proxy:
    build : ./nginx
    container_name : proxy
    #the log server is accessible by 8080 port and redirected to 80
    ports:
      - "8081:81"
    networks:
      - elknet

  logstash:
    build : ./logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044/tcp"
      - "5044:5044/udp"
      - "9600:9600"
    environment:
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    networks:
      - elknet

  filebeat:
    build : ./filebeat
    #to avoid errors as filebeat starts in few ms
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
      logstash:
        condition: service_healthy
    volumes:
      - ./filebeat/config/filebeat.yml:/etc/filebeat/filebeat.yml
      - ./logs:/logs
    environment:
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    networks:
      - elknet
    depends_on:
      - elasticsearch
    restart: unless-stopped
    links:
      - "elasticsearch"
      - "kibana"
      - "logstash"

networks:
  public_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
  elknet:

volumes:
  esdata:
    driver: local